name: deploy on heroku pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types:  [opened , synchronize]
  schedule:
    - cron: '20 5 * * *'

jobs:
  deploying:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install and lint
        run : |
          npm install
          npm run lint
      - name: deploy to heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message) , '#skip') }}
        uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "myphonebook11"
          heroku_email: "yousaf.syed5@gmail.com"
          healthcheck: "https://myphonebook11.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true

  health-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Checking the deployed application-url
        uses: jtalk/url-health-check-action@v1.4
        with:
          url: "https://myphonebook11.herokuapp.com/health"
          max-attempts: 2
          retry-delay: 4s
      
