name: deploy on heroku pipeline

on:
  push:
    branches:
      -main

jobs:
  checking working:
    steps:
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@v2
      - name: outputing date and ls
        run: |
          date
          ls

